import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {escape as esc, labels, readContent, validate, markdown, validatePrices, priceStats} from './content.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const config=JSON.parse(fs.readFileSync(path.join(root,'site.config.json'),'utf8'));
const articles=readContent(path.join(root,'content/articles')).sort((a,b)=>b.published.localeCompare(a.published));
const editions=readContent(path.join(root,'content/editions')).sort((a,b)=>b.slug.localeCompare(a.slug));
validate(articles,editions,config);
const prices=JSON.parse(fs.readFileSync(path.join(root,'data/prices.json'),'utf8'));validatePrices(prices);
const base=process.env.SITE_URL || config.url;
if(!/^https?:\/\//.test(base)||!base.endsWith('/'))throw new Error('SITE_URLは末尾 / の絶対URLにしてください');
const basePath=new URL(base).pathname;
const href=p=>basePath+p;
const out=path.join(root,'dist');fs.mkdirSync(out,{recursive:true});
// Remove only previous generated output files, never content.
for(const entry of fs.readdirSync(out,{withFileTypes:true}))fs.rmSync(path.join(out,entry.name),{recursive:true,force:true});
const write=(p,text)=>{fs.mkdirSync(path.dirname(path.join(out,p)),{recursive:true});fs.writeFileSync(path.join(out,p),text);};
const get=slug=>articles.find(a=>a.slug===slug);
const articleURL=a=>href(`articles/${a.slug}/`);
const date=t=>new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date(t));
const tags=a=>`<div class="tags">${a.tags.map(tag=>`<a href="${href('topics/')}?tag=${encodeURIComponent(tag)}">#${esc(tag)}</a>`).join('')}</div>`;
const badge=a=>`<span class="badge ${esc(a.status)}">${esc(labels[a.status])}</span>`;
const card=a=>`<article class="card"><div class="eyebrow">${esc(config.categories[a.category])} ${badge(a)}</div><h3><a href="${articleURL(a)}">${esc(a.title)}</a></h3><p>${esc(a.summary)}</p>${tags(a)}<a class="readmore" href="${articleURL(a)}">記事を読む <span aria-hidden="true">↗</span></a></article>`;
const linkList=list=>`<div class="cards">${list.map(card).join('')}</div>`;
const weather=`<aside class="weather" aria-labelledby="weather-title"><div class="eyebrow">LOCAL WEATHER</div><h2 id="weather-title">今日のいちき串木野</h2><div id="weather-data" role="status"><p>予報を読み込み中</p></div><p class="small">数値は地域のモデル予報です。<br><a href="https://open-meteo.com/">Open-Meteo</a> · <a href="https://www.jma.go.jp/bosai/forecast/#area_type=offices&amp;area_code=460000">気象庁の予報・防災情報 ↗</a></p></aside>`;
function layout(title,body,p='',description=config.subtitle){
 const nav=Object.entries(config.categories).map(([key,label])=>`<a ${p===`categories/${key}/`?'aria-current="page"':''} href="${href(`categories/${key}/`)}">${esc(label)}</a>`).join('');
 return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | JAMIO NEWS</title><meta name="description" content="${esc(description)}"><meta name="color-scheme" content="light dark"><link rel="canonical" href="${esc(new URL(p,base).href)}"><link rel="alternate" type="application/rss+xml" title="じゃみお朝刊 RSS" href="${href('rss.xml')}"><link rel="icon" type="image/svg+xml" href="${href('assets/icon.svg')}"><script src="${href('assets/theme.js')}"></script><link rel="stylesheet" href="${href('assets/style.css')}"><script type="module" src="${href('assets/app.js')}"></script></head><body><a class="skip" href="#main">本文へ</a><div class="page"><header><div class="mast-top"><span>AI · HARDWARE · KAGOSHIMA</span><div><a href="${href('rss.xml')}">RSS</a><button id="theme" aria-label="表示テーマを切り替える">◐ <span>テーマ</span></button></div></div><div class="mast"><a class="brand" href="${href('')}">JAMIO<span>NEWS</span><i>じゃみお新聞</i></a><p>${esc(config.subtitle)}<br><span>AI・PC・鹿児島に偏った、あなた専用新聞。</span></p></div><nav aria-label="カテゴリ">${nav}<a href="${href('archive/')}">過去号アーカイブ</a><a href="${href('topics/')}">注目テーマ</a><a href="${href('search/')}">検索 <span aria-hidden="true">⌕</span></a></nav></header><main id="main">${body}</main><footer><a class="footer-brand" href="${href('')}">JAMIO NEWS</a><p>早さに、確かさを添えて。<br>Xは発見の入口。出典と確認状態を、記事とともに残します。</p><div><a href="${href('policy/')}">編集方針</a><a href="${href('prices/')}">価格履歴</a><a href="${href('rss.xml')}">RSS</a><a href="${href('archive/')}">過去号</a></div><small>時刻は日本時間（JST）。ニュース・価格は掲載時点の情報です。</small></footer></div></body></html>`;
}
const latest=editions[0];
if(!latest)throw new Error('最低1件の朝刊を用意してください');
const front=get(latest.hero);
const issueNotice=e=>e.kind==='launch'?'<div class="notice">開設号：この号の記事は編集方針・読み方のガイドです。最新ニュースの収集と毎朝の自動配信は、まだ開始していません。</div>':'';
const topFive=e=>`<section class="top-five"><div class="section-title"><h2>3分で読むトップ5</h2><span>${e.kind==='launch'?'開設号 · まずは読み方から':'MORNING BRIEF'}</span></div><ol>${e.top5.map((s,i)=>{const a=get(s);return `<li><span class="number">0${i+1}</span><div><div class="eyebrow">${esc(config.categories[a.category])} ${badge(a)}</div><h3><a href="${articleURL(a)}">${esc(a.title)}</a></h3><p>${esc(a.summary)}</p></div></li>`;}).join('')}</ol></section>`;
write('index.html',layout('今日の朝刊',`<div class="edition-line"><span><span class="live-dot"></span> 最新号</span><time datetime="${esc(latest.published)}">${date(latest.published)}</time><a href="${href(`editions/${latest.slug}/`)}">${esc(latest.title)}の完全版 ↗</a></div>${issueNotice(latest)}<div class="front-grid"><section class="front"><div class="eyebrow">THE FRONT PAGE <span>一面</span></div><h1><a href="${articleURL(front)}">${esc(front.title)}</a></h1><p class="front-summary">${esc(front.summary)}</p><div class="front-bottom">${badge(front)}<a class="button" href="${articleURL(front)}">一面を読む ↗</a></div><div class="front-art" aria-hidden="true"><span class="art-label">JMN / DAILY PERSPECTIVE</span><div class="orb"></div><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="art-foot">好奇心の、その先へ。</span></div></section>${weather}</div>${topFive(latest)}<section class="deal-section"><div class="section-title"><h2>重要セール &amp; 価格ウォッチ</h2><a href="${href('prices/')}">価格履歴 ↗</a></div>${latest.deals.length?linkList(latest.deals.map(get)):'<div class="empty"><span class="eyebrow">WATCHING THE MARKET</span><h3>購入判断に効く動きだけを。</h3><p>現在、確認済みのセール掲載はありません。約10％以上の相場変動、過去安値級、実質値引き、在庫復活を追います。</p></div>'}<div class="watch-tags">${['GPU','CPU','大容量RAM','SSD','Strix Halo','GB10 / DGX Spark / RTX Spark'].map(t=>`<a href="${href('topics/')}?tag=${encodeURIComponent(t)}">${esc(t)}</a>`).join('')}</div></section><section><div class="section-title"><h2>各面から</h2><a href="${href('archive/')}">アーカイブ ↗</a></div>${linkList(articles.slice(0,6))}</section>`));
for(const a of articles){
 const sources=(a.sources??[]).map(s=>`<li><span class="source-type">${esc(s.type)}</span> <a href="${esc(s.url)}" rel="noopener noreferrer">${esc(s.title)} ↗</a><small>確認: ${esc(s.checked)}</small></li>`).join('');
 write(`articles/${a.slug}/index.html`,layout(a.title,`<div class="breadcrumb"><a href="${href('')}">トップ</a> / <a href="${href(`categories/${a.category}/`)}">${esc(config.categories[a.category])}</a></div><article class="reading"><div class="eyebrow">${esc(config.categories[a.category])} ${badge(a)}</div><h1>${esc(a.title)}</h1><p class="lede">${esc(a.summary)}</p><div class="article-meta"><time datetime="${esc(a.published)}">${date(a.published)}</time><span>${Math.max(1,Math.ceil(a.body.length/600))}分で読む</span>${a.updated?`<span>更新 ${esc(a.updated)}</span>`:''}</div>${tags(a)}${a.status==='unconfirmed'?'<div class="notice">未確認情報です。投稿・主張の存在と、その内容の正しさを分けて読んでください。</div>':''}${a.verificationNote?`<aside class="verification"><strong>検証メモ</strong><p>${esc(a.verificationNote)}</p></aside>`:''}<div class="prose">${markdown(a.body)}</div>${a.corrections?`<aside class="verification"><strong>訂正履歴</strong><p>${esc(a.corrections)}</p></aside>`:''}<section class="sources"><h2>${a.kind==='guide'?'このガイドについて':'出典と確認状況'}</h2>${sources?`<ul>${sources}</ul>`:'<p>開設号の編集方針です。製品発表や現在価格についてのニュースではありません。</p>'}<p>確認済み＝一次資料で確認。報道＝報道機関による情報。未確認＝裏取りが完了していない主張。本文中の考察・購入判断は編集部の見解です。</p></section><a class="back-link" href="${href('')}">← 朝刊へ戻る</a></article>`,`articles/${a.slug}/`,a.summary));
}
for(const e of editions)write(`editions/${e.slug}/index.html`,layout(e.title,`<div class="page-title"><div class="eyebrow">JAMIO MORNING NEWS</div><h1>${esc(e.title)}</h1><p>${date(e.published)} · ${e.articles.length}記事 · 日本時間</p></div>${issueNotice(e)}<div class="prose issue-intro">${markdown(e.body)}</div>${topFive(e)}<section><div class="section-title"><h2>この号の全記事</h2></div>${linkList(e.articles.map(get))}</section>`,`editions/${e.slug}/`));
for(const [key,label]of Object.entries(config.categories))write(`categories/${key}/index.html`,layout(label,`<div class="page-title"><div class="eyebrow">SECTION / ${esc(key.toUpperCase())}</div><h1>${esc(label)}</h1><p>発表の先にある、じゃみおへの影響まで。</p></div>${articles.some(a=>a.category===key)?linkList(articles.filter(a=>a.category===key)):'<div class="empty">この面の記事はまだありません。情報を確認でき次第掲載します。</div>'}`,`categories/${key}/`));
write('archive/index.html',layout('過去号アーカイブ',`<div class="page-title"><div class="eyebrow">THE ARCHIVE</div><h1>朝刊を、積み重ねる。</h1><p>日付ごとに、その日のトップ5と完全版を残します。</p></div><div class="archive-list">${editions.map(e=>`<a href="${href(`editions/${e.slug}/`)}"><time>${esc(e.slug)}</time><strong>${esc(e.title)}</strong><span>${e.articles.length}記事 ↗</span></a>`).join('')}</div>`,'archive/'));
const searchUI=topic=>`<div class="page-title"><div class="eyebrow">${topic?'FOLLOW YOUR CURIOSITY':'FIND A STORY'}</div><h1>${topic?'注目テーマ':'記事を探す'}</h1><p>タイトル・本文・タグをまとめて検索。</p></div>${topic?`<div class="topic-cloud">${config.topics.map(t=>`<a href="?tag=${encodeURIComponent(t)}">${esc(t)}</a>`).join('')}</div>`:''}<form id="search-form"><label for="query">キーワード</label><div class="search-bar"><input id="query" type="search" placeholder="OpenAI、ローカルLLM、GPU…" autocomplete="off"><button class="button" type="submit">検索</button></div><div class="filters"><label>カテゴリ <select id="category"><option value="">すべて</option>${Object.entries(config.categories).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('')}</select></label><label>確認状態 <select id="status"><option value="">すべて</option>${Object.entries(labels).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('')}</select></label></div></form><p id="search-count" role="status"></p><div id="results" class="cards"></div><noscript><p>検索にはJavaScriptが必要です。カテゴリと過去号から記事を読めます。</p></noscript>`;
write('search/index.html',layout('記事検索',searchUI(false),'search/'));
write('topics/index.html',layout('注目テーマ',searchUI(true),'topics/'));
const verdicts={buy:'買い',conditional:'条件付きで買い',wait:'様子見'};
const stats=[...new Set(prices.map(r=>r.product))].map(p=>priceStats(prices,p));
write('prices/index.html',layout('価格履歴',`<div class="page-title"><div class="eyebrow">PRICE OBSERVATORY</div><h1>安い、には根拠を。</h1><p>GPU・RAM・AI PCの観測履歴。税込・送料込みの実支払額で比較します。</p></div>${!stats.length?'<div class="empty"><h2>価格の観測を待っています</h2><p>現在価格・30日前比・観測期間の最安値は、実売価格を確認してから掲載します。架空の価格や値引き率は使いません。</p></div>':stats.map(s=>`<section class="price-product"><h2>${esc(s.current.product)}</h2><div class="price-summary"><strong>¥${s.current.total.toLocaleString('ja-JP')}</strong><span>30日前比 ${s.change===null?'比較データ不足':s.change.toFixed(1)+'%'}</span><span>観測最安 ¥${s.low.toLocaleString('ja-JP')}</span><span>${verdicts[s.current.verdict]}</span></div><p>${esc(s.current.reason)}</p><p>観測 ${esc(s.current.observed)} · ${esc(s.current.shop)} · ${esc(s.current.condition)}</p><p><a href="${esc(s.current.url)}">販売店で現在価格・在庫を確認 ↗</a></p><div class="table-wrap"><table><caption>${esc(s.current.product)}の価格履歴</caption><thead><tr><th>観測日時</th><th>税込送料込</th><th>店舗 / SKU</th><th>条件</th></tr></thead><tbody>${s.history.slice().reverse().map(r=>`<tr><td>${esc(r.observed)}</td><td>¥${r.total.toLocaleString('ja-JP')}</td><td><a href="${esc(r.url)}">${esc(r.shop)} / ${esc(r.sku)}</a></td><td>${esc(r.condition)}</td></tr>`).join('')}</tbody></table></div></section>`).join('')}<div class="verification"><h2>比較のルール</h2><p>30日前比は同一SKU・店舗・購入条件の記録を比較。30日前以前の最も近い記録（7日以内）がなければ「比較データ不足」。最安値は当サイトの観測範囲に限り、市場全体の最安値ではありません。期限切れ価格を現在価格として扱わないよう、観測時刻を必ず表示します。</p></div>`,'prices/'));
const policy=fs.readFileSync(path.join(root,'docs/editorial-policy.md'),'utf8');write('policy/index.html',layout('編集方針',`<div class="reading prose">${markdown(policy)}</div>`,'policy/'));
write('404.html',layout('ページが見つかりません','<div class="page-title"><h1>このページは見つかりませんでした。</h1><p><a href="'+href('')+'">トップページへ戻る</a></p></div>','404.html'));
write('search.json',JSON.stringify(articles.map(a=>({title:a.title,summary:a.summary,body:a.body,tags:a.tags,category:a.category,categoryLabel:config.categories[a.category],status:a.status,statusLabel:labels[a.status],url:articleURL(a)}))));
const rssItems=[...editions.map(e=>({title:e.title,url:new URL(`editions/${e.slug}/`,base).href,date:e.published,description:e.kind==='launch'?'開設号：編集方針と読み方ガイド。最新ニュースではありません。':e.top5.map(s=>get(s).title).join(' / ')})),...articles.map(a=>({title:`[${labels[a.status]}] ${a.title}`,url:new URL(`articles/${a.slug}/`,base).href,date:a.published,description:a.summary}))].sort((a,b)=>b.date.localeCompare(a.date));
write('rss.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>じゃみお朝刊 / JAMIO NEWS</title><link>${esc(base)}</link><description>${esc(config.subtitle)}</description><language>ja</language><atom:link href="${esc(new URL('rss.xml',base).href)}" rel="self" type="application/rss+xml"/>${rssItems.map(i=>`<item><title>${esc(i.title)}</title><link>${esc(i.url)}</link><guid isPermaLink="true">${esc(i.url)}</guid><pubDate>${new Date(i.date).toUTCString()}</pubDate><description>${esc(i.description)}</description></item>`).join('')}</channel></rss>`);
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['', 'archive/','topics/','search/','prices/','policy/',...Object.keys(config.categories).map(k=>`categories/${k}/`),...articles.map(a=>`articles/${a.slug}/`),...editions.map(e=>`editions/${e.slug}/`)].map(p=>`<url><loc>${esc(new URL(p,base).href)}</loc></url>`).join('')}</urlset>`);
write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${new URL('sitemap.xml',base).href}\n`);write('.nojekyll','');
fs.cpSync(path.join(root,'public'),out,{recursive:true});
console.log(`Built ${articles.length} articles, ${editions.length} editions → ${out}`);
